# Generated by Django 6.0.4 on 2026-06-03 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('SUMMARY', 'Summary'), ('ACTION_ITEM', 'Action Item'), ('DECISION', 'Decision'), ('FOLLOWUP', 'Follow-up Suggestion')], max_length=20)),
                ('content', models.TextField()),
                ('assignee', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'analysis_items',
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=20)),
                ('speaker', models.CharField(blank=True, max_length=255)),
                ('text_excerpt', models.TextField(blank=True)),
                ('analysis_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='analysis.analysisitem')),
            ],
            options={
                'db_table': 'citations',
            },
        ),
        migrations.CreateModel(
            name='MeetingAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='meetings.meeting')),
            ],
            options={
                'db_table': 'meeting_analyses',
            },
        ),
        migrations.AddField(
            model_name='analysisitem',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='analysis.meetinganalysis'),
        ),
    ]
